version: '3.7'
services:
  psql:
    container_name: psql
    build: ./db
    image: jobsdb:latest
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=aaa
      - POSTGRES_PASSWORD=password
  server:
    container_name: server
    build: ./django
    image: jobs:latest
    ports:
      - 8000:8000
    depends_on: 
      - psql
    volumes: 
      - ./django:/usr/src/app

